XGBoost:
  n_estimators: 100
  max_depth: 3
  eta: 1
  learning_rate: 0.4
  min_child_weight: 1
  subsample: 0.8
  colsample_bytree: 0.8
  reg_lambda: 1

GBDT:
  n_estimators: 600
  learning_rate: 0.2
  max_depth: 7
  min_samples_split: 2
  min_samples_leaf: 1
  subsample: 0.8
  max_features: "sqrt"

RandomForest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: "sqrt"
    bootstrap: True

AdaBoost:
  n_estimators: 1000,
  learning_rate: 0.2,

MLP:
  seq_len: 4
  hidden_dim: 256
  num_layers: 2

CNN:
  seq_len: 4
  kernel_sizes:
    - 2
    - 2
    - 2
  hidden_dim: 256